### ISSUE TITLE
Taiwan is not a province of China.

### ISSUE THREAD

**Issue by mingderwang** [WebReflection/vercel-sqlite-demo#2]
I think you make a mistake in your countries database.

**Comment by WebReflection** [comment]
The data comes from here, I’ve just demoed SQLite on Vercel.

https://lite.ip2location.com/database/ip-country

**Comment by RianQuenlin** [comment]
Well you need to find yourself a different data source, claiming Taiwan belongs to China is like claiming Ukraine belongs to Russia.

**Comment by WebReflection** [comment]
I am not claiming anything at all, I’m not responsible for the data I think you should address the issue to the data provider. The simple version might have smaller ranges of IPs accuracy

**Comment by iszmxw** [comment]
> I think you make a mistake in your countries database.

Taiwan is originally a province of China, and I think you are a big rebel
